[package]
name = "simulation_robots"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"  # ou votre version actuelle
rand = "0.8.5"
noise = "0.8.2" 
ordered-float = "3.0"

[lib]
name = "simulation_robots"
path = "src/lib.rs"
