[package]
name = "simulation_robots"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11"
rand = "0.8"
noise = "0.8"
ordered-float = "3.7.0"

[[bin]]
name = "simulation_robots"
path = "src/main.rs"

[lib]
name = "simulation_robots"
path = "src/lib.rs"

